import Head from 'next/head';
import { Poppins } from 'next/font/google';
import { Center, createStyles } from '@mantine/core';
import { Providers } from '~/components/providers/Providers';
import { useAudioService } from '../hooks/use-audio-service/useAudioService';
import { useEffect, useLayoutEffect, useRef } from 'react';
import { AudioService } from '~/services/audio';
import { useRouter } from 'next/router';
import { Settings } from '~/components/settings';
import { Scene } from '~/components/three/scene/Scene';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '800'],
  subsets: ['latin'],
});

const useStyles = createStyles((theme) => ({
  wrapper: {
    background: 'linear-gradient(to bottom right, #49BCF6 , #49DEB2)',
    width: '100%',
    height: '100vh',
    fontFamily: 'var(--font-poppins)',
  },
}));

export default function Home() {
  useAudioService();

  const audioRef = useRef<HTMLAudioElement>(null);
  const { classes } = useStyles();

  const router = useRouter();

  useEffect(() => {
    if (!AudioService.checkIsInitialized()) {
      router.push('/');
    }
  }, [router]);

  useLayoutEffect(() => {
    if (audioRef.current && AudioService.checkIsInitialized()) {
      const audioService = AudioService.getInstance();

      if (audioService?.isAudioElementLinked()) {
        return;
      }

      audioService?.linkAudioElement(audioRef.current);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Providers>
        <main className={poppins.className}>
          <Center className={classes.wrapper}>
            <Scene />
          </Center>
          <Settings />
        </main>
      </Providers>
    </>
  );
}
