name: Automated Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      # The automated tests were initially in the pipeline, however since this is a public repository,
      # I didn't want to include DB secretes in the pipeline (with Github repository secrets everything probably
      # would be safe, but I didn't want to take any risks just in case ).
      # Therefore, the tests were only run locally before every push to the remote.
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: yarn playwright test
